'use strict';
const E=FleetEngine,$=id=>document.getElementById(id), TYPES=E.TYPES;
const defaults=()=>Object.fromEntries(TYPES.map(([id,name],i)=>[id,{name,color:['#889c91','#899ba5','#99998a','#697e76','#8e9b9e'][i],accent:'#c5b477',hull:'classic',pattern:'deck',insignia:'bars',wake:true}]));
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback;}catch{return fallback;}}
let designs=read('fleet98-designs',defaults()),record=read('fleet98-record',{wins:0,losses:0}),prefs=read('fleet98-options',{sound:false,theme:'classic',motion:true});
for(let [id] of TYPES)designs[id]={...defaults()[id],...designs[id]};
let game=null,selected='carrier',yardSelected='carrier',vertical=false,timer=null,hover={own:null,enemy:null},fx=null,audio=null;
const reduced=()=>!prefs.motion||matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{$('statusbar').textContent='Storage unavailable - keep this window open.';}}
function persist(){save('fleet98-match',game);}
function log(message){game.log.unshift(message);game.log=game.log.slice(0,60);}
function newGame(){clearTimeout(timer);timer=null;fx=null;game={version:1,phase:'deploy',turn:'player',own:E.fleet(),enemy:E.fleet(),out:{},incoming:{},remaining:[5,4,3,3,2],difficulty:$('difficulty').value,round:0,log:['Command link established.','Fleet ready for deployment.'],message:'Fleet assembled. Customize your ships or begin an operation.'};persist();render();}
function requestNew(){if(game.phase==='battle')$('confirm').showModal();else newGame();}
function coord(c){return 'ABCDEFGHIJ'[Math.floor(c/10)]+(c%10+1);}
function alive(ships,shots){return ships.filter(s=>!s.cells.every(c=>shots[c])).length;}
function tone(hit,sunk){if(!prefs.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=hit?'sawtooth':'sine';o.frequency.setValueAtTime(sunk?110:hit?190:500,audio.currentTime);o.frequency.exponentialRampToValueAtTime(40,audio.currentTime+.22);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.3);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.31);}catch{}}
function begin(){game.phase='battle';game.difficulty=$('difficulty').value;game.message='Your move. Select a coordinate in enemy waters.';log('Operation started. '+game.difficulty.toUpperCase()+' opponent.');persist();render();}
function shoot(c){if(game.phase!=='battle'||game.turn!=='player')return;let result=E.fire(game.enemy,game.out,c);if(!result)return;game.round++;game.turn='ai';log('YOU > '+coord(c)+' / '+(result.sunk?'VESSEL SUNK':result.hit?'HIT':'MISS'));game.message=result.sunk?'Enemy vessel sunk.':result.hit?'Direct hit. Enemy responding…':'Shot fell wide. Enemy responding…';tone(result.hit,result.sunk);animate('enemy',c,result.hit);if(result.won){finish(true);return;}persist();render();timer=setTimeout(aiTurn,reduced()?250:850);}
function aiTurn(){if(game.phase!=='battle'||game.turn!=='ai')return;let c=E.chooseShot(game.incoming,game.remaining,game.difficulty);let result=E.fire(game.own,game.incoming,c);if(!result)return;if(result.sunk){const len=game.own.find(s=>s.id===result.sunk).len;game.remaining.splice(game.remaining.indexOf(len),1);}log('ENEMY > '+coord(c)+' / '+(result.sunk?'OUR VESSEL SUNK':result.hit?'HIT':'MISS'));tone(result.hit,result.sunk);animate('own',c,result.hit);if(result.won){finish(false);return;}game.turn='player';game.message=result.sunk?'We lost '+designs[result.sunk].name+'. Your move.':result.hit?'Our fleet took a hit. Your move.':'Enemy shell missed. Your move.';persist();render();}
function finish(won){game.phase=won?'won':'lost';game.turn='none';record[won?'wins':'losses']++;save('fleet98-record',record);game.message=won?'Victory. All five enemy vessels destroyed.':'Fleet lost. Enemy positions are now revealed.';log(won?'OPERATION COMPLETE / VICTORY':'OPERATION COMPLETE / DEFEAT');persist();render();showInfo(won?'Mission accomplished':'Fleet lost',`<h2>${won?'The ocean is yours.':'All hands remembered.'}</h2><p>${won?'All five enemy ships have been sunk.':'Your fleet has been destroyed. Review the revealed enemy grid and try a new deployment.'}</p><p>Rounds: ${game.round} · Accuracy: ${Math.round(Object.values(game.out).filter(x=>x!=='miss').length/Math.max(1,Object.keys(game.out).length)*100)}%</p><button id="again">Deploy again</button>`);$('again').onclick=()=>{$('info').close();newGame();};}
function render(){const deploy=game.phase==='deploy',battle=game.phase==='battle';$('deployment').hidden=!deploy;$('deployment').style.display=deploy?'flex':'none';$('cover').style.display=deploy?'flex':'none';$('difficulty').disabled=battle;$('phase').textContent=deploy?'DEPLOYMENT':battle?'ENGAGED':game.phase==='won'?'VICTORY':'FLEET LOST';$('missionSub').textContent=deploy?'Prepare your fleet.':battle?'Weapons free.':'Operation complete.';$('turnNumber').textContent=String(game.round).padStart(2,'0');$('turnLabel').textContent=deploy?'STANDBY':battle?(game.turn==='player'?'YOUR MOVE':'ENEMY MOVE'):'COMPLETE';$('status').textContent=game.message;$('statusbar').textContent=deploy?'Deployment | '+designs[selected].name+' | '+(vertical?'Vertical':'Horizontal'):battle?game.difficulty.toUpperCase()+' | '+(game.turn==='player'?'Select enemy coordinate':'Enemy targeting…'):'Operation complete';$('ownCount').textContent=alive(game.own,game.incoming)+' vessels afloat';$('enemyCount').textContent=alive(game.enemy,game.out)+' vessels afloat';const h=Object.values(game.out).filter(x=>x!=='miss').length;$('hits').textContent=h;$('accuracy').textContent=Math.round(h/Math.max(1,Object.keys(game.out).length)*100)+'%';$('sunk').textContent=(5-alive(game.enemy,game.out))+'/5';$('record').textContent=`LOCAL RECORD ${record.wins} W / ${record.losses} L`;$('ownHint').textContent=deploy?'Select ship • tap to place • R / Rotate to turn':'Your fleet / enemy impact tracking';$('targetHint').textContent=deploy?'Targeting system offline.':battle?(game.turn==='player'?'Click or tap a coordinate to fire.':'Incoming enemy transmission…'):'All enemy positions revealed.';$('log').replaceChildren(...game.log.map(t=>{let li=document.createElement('li');li.textContent=t;return li;}));$('fleetStrip').replaceChildren(...TYPES.map(([id,name,len])=>{let b=document.createElement('button');b.className=id===selected?'selected':'';let s=document.createElement('strong'),small=document.createElement('small');s.textContent=designs[id].name;small.textContent=game.own.find(x=>x.id===id).cells.every(c=>game.incoming[c])?'SUNK':name+' / '+len;b.append(s,small);b.onclick=()=>{selected=id;vertical=game.own.find(s=>s.id===id).vertical;render();};return b;}));drawBoards();}
// Procedural top-down ship art: one renderer for board and workshop.
function ship(ctx,cx,cy,length,width,design,rotation=0){ctx.save();ctx.translate(cx,cy);ctx.rotate(rotation);const L=length,W=width;ctx.shadowColor='#0009';ctx.shadowBlur=4;ctx.shadowOffsetY=3;
if(design.wake){ctx.fillStyle='#9fbeb526';ctx.beginPath();ctx.moveTo(-L*.48,-W*.34);ctx.lineTo(-L*.67,-W*.65);ctx.lineTo(-L*.62,W*.65);ctx.lineTo(-L*.48,W*.34);ctx.fill();}
ctx.beginPath();const shoulder=design.hull==='heavy'?.38:.3;ctx.moveTo(L*.5,0);ctx.lineTo(L*shoulder,-W*.48);ctx.lineTo(-L*.43,-W*.48);ctx.lineTo(-L*.5,-W*.23);ctx.lineTo(-L*.5,W*.23);ctx.lineTo(-L*.43,W*.48);ctx.lineTo(L*shoulder,W*.48);ctx.closePath();ctx.fillStyle=design.color;ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.strokeStyle='#dce6db';ctx.lineWidth=1.3;ctx.stroke();ctx.save();ctx.clip();ctx.fillStyle=design.accent;
if(design.pattern==='stripe')ctx.fillRect(-L/2,-W*.08,L,W*.16);
if(design.pattern==='dazzle'){for(let i=-3;i<4;i++){ctx.beginPath();ctx.moveTo(i*L/5,-W);ctx.lineTo(i*L/5+L/8,-W);ctx.lineTo(i*L/5+L/3,W);ctx.lineTo(i*L/5+L/5,W);ctx.fill();}}
if(design.pattern==='deck'){ctx.globalAlpha=.4;ctx.fillRect(-L*.38,-W*.3,L*.68,W*.6);ctx.globalAlpha=1;}
ctx.restore();ctx.fillStyle='#283b39';ctx.fillRect(-L*.16,-W*.29,L*.28,W*.58);ctx.fillStyle=design.hull==='angular'?'#566961':'#a6b1a6';ctx.fillRect(-L*.1,-W*.22,L*.17,W*.44);ctx.fillStyle='#192924';ctx.fillRect(-L*.075,-W*.15,L*.085,W*.3);ctx.strokeStyle='#dce4ca';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-L*.015,-W*.33);ctx.lineTo(-L*.015,W*.33);ctx.stroke();
for(let p of [L*.25,-L*.3]){ctx.fillStyle='#334844';ctx.beginPath();if(design.hull==='angular')ctx.rect(p-W*.16,-W*.2,W*.32,W*.4);else ctx.arc(p,0,W*.22,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#b5c2b2';ctx.lineWidth=W*.07;for(let q of [-.075,.075]){ctx.beginPath();ctx.moveTo(p,q*W);ctx.lineTo(p+W*.42,q*W);ctx.stroke();}}
ctx.fillStyle=design.accent;ctx.font='bold '+W*.3+'px monospace';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText({none:'',star:'★',cross:'+',bars:'≡'}[design.insignia],-L*.4,0);ctx.restore();}
const START=40,CELL=54,SIZE=540;
function drawBoard(id){let canvas=$(id),ctx=canvas.getContext('2d'),shots=id==='own'?game.incoming:game.out,ships=id==='own'?game.own:game.enemy;ctx.clearRect(0,0,600,600);ctx.fillStyle='#102724';ctx.fillRect(0,0,600,600);ctx.fillStyle='#8ba598';ctx.font='12px monospace';ctx.textAlign='center';ctx.textBaseline='middle';for(let i=0;i<10;i++){ctx.fillText(i+1,START+i*CELL+CELL/2,20);ctx.fillText('ABCDEFGHIJ'[i],20,START+i*CELL+CELL/2);}
for(let y=0;y<10;y++)for(let x=0;x<10;x++){ctx.fillStyle=(x+y)%2?'#152f2d':'#173330';ctx.fillRect(START+x*CELL,START+y*CELL,CELL,CELL);ctx.strokeStyle='#547b6a33';ctx.strokeRect(START+x*CELL+.5,START+y*CELL+.5,CELL,CELL);ctx.fillStyle='#72938518';ctx.fillRect(START+x*CELL+13,START+y*CELL+28,13,1);}
for(let s of ships){if(id==='enemy'&&!s.cells.every(c=>shots[c])&&!['won','lost'].includes(game.phase))continue;let d=id==='own'?designs[s.id]:{color:'#8a887e',accent:'#b36350',hull:'angular',pattern:'deck',insignia:'cross',wake:false};ship(ctx,START+s.x*CELL+(s.vertical?CELL/2:s.len*CELL/2),START+s.y*CELL+(s.vertical?s.len*CELL/2:CELL/2),s.len*CELL-12,CELL*.63,d,s.vertical?Math.PI/2:0);}
for(let [key,result]of Object.entries(shots)){let c=+key,x=START+(c%10)*CELL+CELL/2,y=START+Math.floor(c/10)*CELL+CELL/2;if(result==='miss'){ctx.strokeStyle='#9fc3b477';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#9fc3b4';ctx.fillRect(x-2,y-2,4,4);}else{ctx.fillStyle=result==='sunk'?'#2b1919cc':'#bc442ddd';ctx.fillRect(x-12,y-12,24,24);ctx.strokeStyle=result==='sunk'?'#b18c69':'#ffd88e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-7,y-7);ctx.lineTo(x+7,y+7);ctx.moveTo(x+7,y-7);ctx.lineTo(x-7,y+7);ctx.stroke();}}
let c=hover[id];if(c!==null){let cs=[c],valid=true;if(id==='own'&&game.phase==='deploy'){let s=game.own.find(s=>s.id===selected);valid=E.canPlace(game.own,c%10,Math.floor(c/10),s.len,vertical,selected);cs=E.cells(c%10,Math.floor(c/10),s.len,vertical);}ctx.fillStyle=valid?'#bada9d30':'#ff594350';ctx.strokeStyle=valid?'#c9e4a3':'#ff8976';ctx.lineWidth=2;cs.filter(c=>c>=0&&c<100).forEach(c=>{let x=START+c%10*CELL,y=START+Math.floor(c/10)*CELL;ctx.fillRect(x,y,CELL,CELL);ctx.strokeRect(x+2,y+2,CELL-4,CELL-4);});}
if(fx&&fx.board===id){let elapsed=performance.now()-fx.time,t=elapsed/650;if(t<1){let x=START+fx.cell%10*CELL+CELL/2,y=START+Math.floor(fx.cell/10)*CELL+CELL/2;ctx.globalAlpha=1-t;ctx.strokeStyle=fx.hit?'#ffc679':'#c3e4db';ctx.lineWidth=4*(1-t)+1;ctx.beginPath();ctx.arc(x,y,6+t*40,0,Math.PI*2);ctx.stroke();if(fx.hit){ctx.fillStyle='#ffda87';for(let i=0;i<8;i++){let a=i*Math.PI/4;ctx.fillRect(x+Math.cos(a)*t*45-3,y+Math.sin(a)*t*45-3,6,6);}}ctx.globalAlpha=1;}}
}
function drawBoards(){drawBoard('own');drawBoard('enemy');}
function animate(board,cell,hit){if(reduced())return;fx={board,cell,hit,time:performance.now()};function frame(){drawBoards();if(fx&&performance.now()-fx.time<650)requestAnimationFrame(frame);else fx=null;}requestAnimationFrame(frame);}
function eventCell(e,canvas){let r=canvas.getBoundingClientRect(),scale=Math.min(r.width,r.height)/600,ox=(r.width-600*scale)/2,oy=(r.height-600*scale)/2;let x=Math.floor(((e.clientX-r.left-ox)/scale-START)/CELL),y=Math.floor(((e.clientY-r.top-oy)/scale-START)/CELL);return x>=0&&x<10&&y>=0&&y<10?y*10+x:null;}
function act(id,c){if(c===null)return;if(id==='enemy'){shoot(c);return;}if(game.phase!=='deploy')return;let s=game.own.find(s=>s.id===selected),x=c%10,y=Math.floor(c/10);if(!E.canPlace(game.own,x,y,s.len,vertical,s.id)){game.message='Placement blocked. Ships cannot overlap or leave the grid.';render();return;}Object.assign(s,{x,y,vertical,cells:E.cells(x,y,s.len,vertical)});game.message=designs[s.id].name+' positioned at '+coord(c)+'.';persist();render();}
for(let id of ['own','enemy']){let canvas=$(id);canvas.onclick=e=>act(id,eventCell(e,canvas));canvas.onpointermove=e=>{hover[id]=eventCell(e,canvas);drawBoard(id);};canvas.onpointerleave=()=>{hover[id]=null;drawBoard(id);};canvas.onkeydown=e=>{let c=hover[id]??0;const delta={ArrowLeft:-1,ArrowRight:1,ArrowUp:-10,ArrowDown:10};if(e.key in delta){e.preventDefault();hover[id]=Math.max(0,Math.min(99,c+delta[e.key]));$('statusbar').textContent=(id==='own'?'Your waters ':'Target ')+coord(hover[id]);drawBoard(id);}if(e.key==='Enter'||e.key===' '){e.preventDefault();act(id,c);}if(e.key.toLowerCase()==='r'&&game.phase==='deploy'){vertical=!vertical;render();}};}
function yard(){ $('shipyard').showModal();renderYard();}
function renderYard(){let d=designs[yardSelected];$('yardShips').replaceChildren(...TYPES.map(([id,name,len])=>{let b=document.createElement('button');b.textContent=name+' · '+len;b.className=id===yardSelected?'selected':'';b.onclick=()=>{yardSelected=id;renderYard();};return b;}));$('shipName').value=d.name;for(let k of ['hull','color','accent','pattern','insignia'])$(k).value=d[k];$('wake').checked=d.wake;preview();}
function preview(){let ctx=$('preview').getContext('2d');ctx.fillStyle='#162d29';ctx.fillRect(0,0,600,240);ctx.strokeStyle='#6d9b7720';for(let x=0;x<600;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,240);ctx.stroke();}for(let y=0;y<240;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(600,y);ctx.stroke();}let s=TYPES.find(s=>s[0]===yardSelected);ship(ctx,300,110,80*s[2],65,designs[yardSelected]);ctx.fillStyle='#9bbca6';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText(designs[yardSelected].name.toUpperCase()+' / '+s[2]+' CELLS',300,212);}
for(let k of ['shipName','hull','color','accent','pattern','insignia','wake'])$(k).oninput=()=>{let d=designs[yardSelected];d[k==='shipName'?'name':k]=k==='wake'?$(k).checked:k==='shipName'?$(k).value.trim()||TYPES.find(s=>s[0]===yardSelected)[1]:$(k).value;save('fleet98-designs',designs);preview();render();};
$('preset').onclick=()=>{designs=defaults();save('fleet98-designs',designs);renderYard();render();};
function showInfo(title,html){$('infoTitle').textContent=title;$('infoBody').innerHTML=html;$('info').showModal();}
function options(){showInfo('Options - Fleet98',`<h2>Command preferences</h2><p><label>Interface palette <select id="theme"><option value="classic">Classic naval</option><option value="amber">Warm iron</option></select></label></p><p><label><input type="checkbox" id="motion"> Radar and impact animations</label></p><p>Sound can be toggled from the toolbar. Device reduced-motion settings are respected.</p><p>Match progress, ship designs, and your win/loss record save on this device automatically.</p>`);$('theme').value=prefs.theme;$('motion').checked=prefs.motion;$('theme').onchange=()=>{prefs.theme=$('theme').value;applyPrefs();};$('motion').onchange=()=>{prefs.motion=$('motion').checked;applyPrefs();};}
function applyPrefs(){document.body.classList.toggle('amber',prefs.theme==='amber');$('sound').textContent='Sound: '+(prefs.sound?'on':'off');$('sound').setAttribute('aria-pressed',String(prefs.sound));document.querySelector('.radar i').style.animationPlayState=reduced()?'paused':'running';save('fleet98-options',prefs);}
$('new').onclick=$('newToolbar').onclick=requestNew;$('confirmNew').onclick=()=>{$('confirm').close();newGame();};$('workshop').onclick=$('workshopMenu').onclick=$('workshopCard').onclick=yard;$('optionsMenu').onclick=options;$('sound').onclick=()=>{prefs.sound=!prefs.sound;applyPrefs();tone(false,false);};$('help').onclick=()=>showInfo('Fleet98 field manual',`<h2>Find. Fire. Sink.</h2><p>Deploy five ships on the 10 × 10 grid. Select a ship beneath the boards, then tap your waters to move it. Rotate changes its placement direction. Ships may touch, but cannot overlap.</p><p>Begin battle, then fire at enemy coordinates. Both sides fire one shot per turn, even after a hit. A gold cross is a hit; a ring is a miss. Destroy all 17 enemy ship cells to win.</p><p><b>Cadet:</b> random shots. <b>Captain:</b> searches a checkerboard and follows hits. <b>Admiral:</b> scores possible ship positions using hits, misses and remaining ship sizes. No difficulty can see your hidden ships.</p><p>Keyboard: focus either grid, use arrow keys, Enter to place/fire, and R to rotate during deployment. At phone sizes the boards stack vertically.</p><p>Fleet98 1.0.0 by 8BitTrade. Original artwork and sounds. Independent naval strategy game.</p>`);
$('downloads').onclick=()=>showInfo('Install & source',`<h2>Fleet98 on your terms.</h2><p>This edition runs in your browser and can be played offline after its first successful online load.</p><p>Android and Windows packaging projects, automated build workflows, tests and the complete editable source are included in the Fleet98 source bundle.</p><p><a href="https://github.com/BabyCRTTV/notepad98/tree/main/fleet98" target="_blank" rel="noopener">Browse source on GitHub</a> · <a href="https://github.com/BabyCRTTV/notepad98/actions/workflows/fleet98.yml" target="_blank" rel="noopener">Native build downloads</a></p><p>Native packages are separate from browser saves. Android downloads are test builds; Windows downloads are portable apps.</p>`);
$('rotate').onclick=()=>{vertical=!vertical;game.message='Placement direction: '+(vertical?'vertical':'horizontal')+'. Tap your grid to apply.';render();};$('shuffle').onclick=()=>{game.own=E.fleet();persist();render();};$('start').onclick=begin;$('difficulty').onchange=()=>{game.difficulty=$('difficulty').value;persist();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
const restored=read('fleet98-match',null);if(restored&&restored.version===1&&restored.own?.length===5&&restored.enemy?.length===5){game=restored;$('difficulty').value=game.difficulty;render();if(game.phase==='battle'&&game.turn==='ai')timer=setTimeout(aiTurn,700);}else newGame();applyPrefs();
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('sw.js').catch(()=>{});
